Add get specifications methods
ni/nitsm-python pull request #161
Opened 2022-04-22 15:48 UTC by smooresni

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nitsm-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds the `get_specifications_value` and `get_specifications_values` methods.

### Why should this Pull Request be merged?

Needed to complete #160 

### What testing has been done?

Created new system test to validate methods.

- [x] I have run the automated tests (required if there are code changes)

2022-04-22 15:50 UTC, smooresni commented
/azp run

2022-04-22 16:09 UTC, smooresni commented
/azp run

2022-04-27 18:49 UTC, ni-erikcrank commented
Please update [STATUS.md](https://github.com/ni/nitsm-python/blob/main/STATUS.md) to include information for GetSpecificationsValues.

2022-04-27 18:50 UTC, ni-erikcrank requested changes

2022-04-27 18:50 UTC, ni-erikcrank commented on src/nitsm/tsmcontext.py
> +    def get_specifications_values(self, namespaced_symbols: "_Sequence[str]") -> "_Tuple[str]":
```suggestion
    def get_specifications_values(self, namespaced_symbols: "_Sequence[str]") -> "_StringTuple":
```

2022-04-27 19:14 UTC, smooresni commented on src/nitsm/tsmcontext.py
> +    def get_specifications_values(self, namespaced_symbols: "_Sequence[str]") -> "_Tuple[str]":
https://github.com/ni/nitsm-python/pull/161/commits/af8d6bfcc1112c73a82393b5d3110e487c787f71

2022-04-27 19:16 UTC, smooresni commented
> Please update [STATUS.md](https://github.com/ni/nitsm-python/blob/main/STATUS.md) to include information for GetSpecificationsValues.

I also took the opportunity to fix some of the formatting in `STATUS.md`

2022-04-27 19:17 UTC, smooresni commented
/azp run

2022-04-27 19:18 UTC, ni-erikcrank approved these changes

2022-04-27 19:44 UTC, merged